---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## Rabbitmq Options
rabbitmq_password: passwd
rabbitmq_cookie_token: NYPZkqTeP8hO

## Tokens
memcached_encryption_key: NYPZkqTeP8hO

## Container default user
container_openstack_password: passwd

## Galera Options
galera_root_password: passwd

## Keystone Options
keystone_container_mysql_password: passwd
keystone_auth_admin_token: 5c28254dc9f815cfaefd
keystone_auth_admin_password: passwd
keystone_service_password: passwd

## Cinder Options
cinder_container_mysql_password: passwd
cinder_service_password: passwd
cinder_v2_service_password: passwd
cinder_profiler_hmac_key: NYPZkqTeP8hO

## Glance Options
glance_container_mysql_password: passwd
glance_service_password: passwd
glance_profiler_hmac_key: NYPZkqTeP8hO

## Heat Options
heat_stack_domain_admin_password: passwd
heat_container_mysql_password: passwd
### THE HEAT AUTH KEY NEEDS TO BE 32 CHARACTERS LONG ##
heat_auth_encryption_key: 5c28254dc9f815cfaefd54dc9f815cfw
### THE HEAT AUTH KEY NEEDS TO BE 32 CHARACTERS LONG ##
heat_service_password: passwd
heat_cfn_service_password: passwd
heat_profiler_hmac_key: NYPZkqTeP8hO

## Horizon Options
horizon_container_mysql_password: passwd
horizon_secret_key: NYPZkqTeP8hO

## Neutron Options
neutron_container_mysql_password: passwd
neutron_service_password: passwd

## Nova Options
nova_container_mysql_password: passwd
nova_metadata_proxy_secret: NYPZkqTeP8hO
nova_ec2_service_password: passwd
nova_service_password: passwd
nova_v3_service_password: passwd
nova_v21_service_password: passwd
nova_s3_service_password: passwd

## Swift Options:
swift_service_password: passwd
swift_container_mysql_password: passwd
swift_dispersion_password: passwd
### Once the swift cluster has been setup DO NOT change these hash values!
swift_hash_path_suffix: jpvdIDNcjM
swift_hash_path_prefix: 0TlTLJ61Z7